version: "3.1"

services:

  database:
    image: postgres:13
    restart: unless-stopped
    environment: 
      POSTGRES_DB: menipage
      POSTGRES_USER: postgres      
      POSTGRES_PASSWORD: berto
    networks:
      - backend-network
    volumes: 
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data

  backend:
    build: backend/
    restart: unless-stopped
    networks: 
      - backend-network
    depends_on: 
      - database
    ports:
      - '3000:3000'
  
networks:
  backend-network:
